# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pub < Formula
  desc "CLI for the Public.com trading API"
  homepage "https://github.com/jonandersen/public-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jonandersen/public-cli/releases/download/v0.3.0/pub_0.3.0_darwin_amd64.tar.gz"
      sha256 "ac997e453b21db72d95d65a5b8c1e71c2f3214ff9061f29ca597b02ba0c5ec81"

      def install
        bin.install "pub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jonandersen/public-cli/releases/download/v0.3.0/pub_0.3.0_darwin_arm64.tar.gz"
      sha256 "1f116b98ee43443f5e6f1e29fd6b9fde1277e72d1a6b92ea17ce811ff900131e"

      def install
        bin.install "pub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonandersen/public-cli/releases/download/v0.3.0/pub_0.3.0_linux_amd64.tar.gz"
      sha256 "07944df8cde8fee2e7ff6687c4aed33a9d408d790186658a666bca1d4924ba6a"
      def install
        bin.install "pub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonandersen/public-cli/releases/download/v0.3.0/pub_0.3.0_linux_arm64.tar.gz"
      sha256 "defe5774cc149d5b24d79e3604578f2d20a6bc015718783748b0d7c89f6b0af1"
      def install
        bin.install "pub"
      end
    end
  end

  test do
    system "#{bin}/pub", "version"
  end
end
