# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pub < Formula
  desc "CLI for the Public.com trading API"
  homepage "https://github.com/jonandersen/public-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jonandersen/public-cli/releases/download/v0.1.0/pub_0.1.0_darwin_amd64.tar.gz"
      sha256 "3c8e5e37517e973d64e4d8d952a857f1ce416f69a5a9fd5e71d36413d4c79d8c"

      def install
        bin.install "pub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jonandersen/public-cli/releases/download/v0.1.0/pub_0.1.0_darwin_arm64.tar.gz"
      sha256 "a985690c86d656f341e132067248a78df12377816e01c4654bc22c0d3c752aaf"

      def install
        bin.install "pub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonandersen/public-cli/releases/download/v0.1.0/pub_0.1.0_linux_amd64.tar.gz"
      sha256 "017e320478dda084b4591e61af737d91249cec6d9606fe9280fcf3557255c31b"
      def install
        bin.install "pub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonandersen/public-cli/releases/download/v0.1.0/pub_0.1.0_linux_arm64.tar.gz"
      sha256 "eeccc03fad869cb7dfa9328e1cf6ab101a5c0ba5f095018633f8c820dd8ea09e"
      def install
        bin.install "pub"
      end
    end
  end

  test do
    system "#{bin}/pub", "version"
  end
end
